[package]
name = "gitbutler-cli"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[[bin]]
name = "gitbutler-cli"
path = "src/main.rs"

[dependencies]
gitbutler-oplog.workspace = true
gitbutler-project.workspace = true
gix.workspace = true
clap = { version = "4.5.9", features = ["derive"] }
anyhow = "1.0.86"
chrono = "0.4.10"
