[package]
name = "gitbutler-cli"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[[bin]]
name = "gitbutler-cli"
path = "src/main.rs"

[dependencies]
gitbutler-core.workspace = true
clap = "4.5.4"
anyhow = "1.0.82"
chrono = "0.4.10"
pager = "0.16.1"
