[package]
name = "but-hunk-dependency"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
anyhow = "1.0.95"
itertools = "0.14.0"
serde.workspace = true
gix = { workspace = true, features = [] }
but-core.workspace = true
but-workspace.workspace = true
gitbutler-serde.workspace = true

[dev-dependencies]
gix-testtools.workspace = true
insta.workspace = true
