[package]
name = "but-workspace"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
bstr.workspace = true
git2.workspace = true
but-core.workspace = true
gitbutler-id.workspace = true
gix = { workspace = true, features = [
    "dirwalk",
    "credentials",
    "parallel",
    "serde",
    "status",
    "revision"
] }
gitbutler-stack.workspace = true
gitbutler-error.workspace = true
gitbutler-command-context.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-commit.workspace = true
gitbutler-repo.workspace = true
serde = { workspace = true, features = ["std"] }
gitbutler-serde.workspace = true
itertools = "0.14"
tracing.workspace = true
tempfile.workspace = true
url = { version = "2.5.4", features = ["serde"] }
md5 = "0.7.0"

[dev-dependencies]
gix-testtools = "0.15.0"
gitbutler-testsupport.workspace = true
insta = "1.42.1"
but-core = { workspace = true, features = ["testing"] }