version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: ["version-update:semver-major"]
    groups:
      npm-minor-updates:
        update-types: [minor]
      npm-patch-updates:
        update-types: [patch]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: ["version-update:semver-major"]
    groups:
      rust-minor-updates:
        update-types: [minor]
      rust-patch-updates:
        update-types: [patch]
