name: init-rust
description: prepare runner for rust related tasks
runs:
  using: "composite"
  steps:
    - name: Cache rust dependencies
      if: runner.name != 'ScottsMacStudio' # internet in berlin is very slow
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: gitbutler-client
        shared-key: rust

    - name: Placeholder for ui assets
      shell: bash
      run: mkdir gitbutler-ui/build

    - name: Check versions
      shell: bash
      run: |
        rustc --version
        cargo --version
        cargo fmt --version
        cargo clippy --version
        git --version
        which git-upload-pack
        which git-upload-archive
        which git-receive-pack
        ssh -V
