[package]
name = "but-db"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false
test = false

[dependencies]
diesel = { version = "2.2.10", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
] }
# Bundled libsqlite3 for Windows
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
serde = { workspace = true, features = ["std"] }
anyhow = "1.0.98"
diesel_migrations = { version = "2.0.0", features = ["sqlite"] }

[dev-dependencies]
tempfile = "3.20.0"
