[package]
name = "but-db"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false
test = false

[dependencies]
diesel = { version = "2.2.11", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
    "chrono",
] }
serde = { workspace = true, features = ["std"] }
anyhow = "1.0.98"
diesel_migrations = { version = "2.0.0", features = ["sqlite"] }
chrono = { version = "0.4.41", features = ["serde"] }
# Needed for bundled libsqlite3 for Windows and hooks
rusqlite = { version = "0.35.0", default-features = false, features = ["hooks", "bundled"]}

[dev-dependencies]
tempfile = "3.20.0"
