[package]
name = "but-path"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false


[lib]
doctest = false

[dependencies]
anyhow = "1.0.99"
dirs = "6.0.0"
