[package]
name = "gitbutler-analytics"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
gitbutler-core.workspace = true
thiserror.workspace = true
tracing = "0.1.40"
tokio = { workspace = true, features = [ "sync" ] }
serde.workspace = true
serde_json = { version = "1.0", features = [ "std", "arbitrary_precision" ] }

async-trait = "0.1.79"
chrono = { version = "0.4.37", features = ["serde"] }
reqwest = { version = "0.12.2", features = ["json"] }

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
