[package]
name = "but-testsupport"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
gix.workspace = true
anyhow.workspace = true
termtree = "0.5.1"
gix-testtools = "0.15.0"

[dev-dependencies]
