[package]
name = "but-feedback"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
test = false
doctest = false

[dependencies]
anyhow = "1.0.99"
zip = "2.2.0"
walkdir = "2.5.0"
chrono = { version = "0.4.41" }
gitbutler-command-context.workspace = true
but-graph.workspace = true
gitbutler-project.workspace = true

[dev-dependencies]
tempfile.workspace = true
