[package]
name = "but-rebase"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
gix.workspace = true
anyhow.workspace = true
bstr.workspace = true
git2.workspace = true
itertools = "0.14"

[[test]]
name = "rebase"
path = "tests/mod.rs"

[dev-dependencies]
gix-testtools.workspace = true
