[package]
name = "gitbutler-watcher"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
gitbutler-core.workspace = true
thiserror.workspace = true
anyhow = "1.0.82"
futures = "0.3.30"
tokio = { workspace = true, features = [ "macros" ] }
tokio-util = "0.7.10"
tracing = "0.1.40"
gix = { workspace = true, features = ["excludes"] }

backoff = "0.4.0"
notify = { version = "6.0.1" }
parking_lot = "0.12.1"
file-id = "0.2.1"
walkdir = "2.2.2"
crossbeam-channel = "0.5.12"
itertools = "0.12"

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
