[package]
name = "gitbutler-changeset"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
thiserror.workspace = true

[dev-dependencies]
paste = "1.0.14"

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
