name: prepare
description: Determine what kind of change has taken place
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: |
          tauri:
            - 'packages/tauri/**'
            - 'packages/butler/**'
            - 'Cargo.lock'
          ui:
            - 'packages/ui/**'
            - 'package.json'
            - 'pnpm-lock.yaml'

    - uses: ./.github/actions/init-env-ui
      if: steps.changes.outputs.ui == 'true'

    - uses: ./.github/actions/init-env-tauri
      if: steps.changes.outputs.tauri == 'true'
