[package]
name = "but-action"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false
test = false

[dependencies]
serde = { workspace = true, features = ["std"] }
serde-error = "0.1.3"
async-openai = "0.28.2"
tokio = { workspace = true, features = ["rt-multi-thread", "io-std"] }
schemars = "0.9.0"
serde_json = "1.0.138"
anyhow = "1.0.98"
chrono = "0.4.41"
uuid = { workspace = true }
strum = { version = "0.27", features = ["derive"] }
gix.workspace = true
gitbutler-command-context.workspace = true
gitbutler-stack.workspace = true
gitbutler-operating-modes.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-branch.workspace = true
gitbutler-oplog.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-project.workspace = true
gitbutler-reference.workspace = true
gitbutler-serde.workspace = true
but-db.workspace = true
but-graph.workspace = true
but-workspace.workspace = true
but-hunk-assignment.workspace = true
