[package]
name = "but"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[[bin]]
name = "but"
path = "src/main.rs"
doctest = false

[features]

[dependencies]
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "io-std"] }
clap = { version = "4.5.37", features = ["derive", "env"] }
anyhow.workspace = true
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main" }
