[package]
name = "but-core"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
serde = { workspace = true, features = ["std"] }
bstr.workspace = true
tracing.workspace = true
anyhow = "1.0.95"
gix = { workspace = true, features = ["dirwalk", "credentials", "parallel", "serde", "status"] }
gitbutler-serde.workspace = true

[dev-dependencies]
gix-testtools.workspace = true
gix = { workspace = true, features = ["revision"] }
serde_json = "1.0"
insta.workspace = true
