[package]
name = "gitbutler-stack"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
anyhow.workspace = true
gitbutler-command-context.workspace = true
gitbutler-branch.workspace = true
gitbutler-reference.workspace = true
gitbutler-repo.workspace = true
itertools = "0.13"

[dev-dependencies]
pretty_assertions = "1.4"
gitbutler-testsupport.workspace = true
tempfile = "3.10.1"
