name: "publish"
on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, macos-aarch64]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x
          run_install: |
            args: ["--frozen-lockfile"]

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      # TODO: figure out how to build aarch64 git on x86_64 runner
      - name: Build git
        run: cd src-tauri/binaries && make

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: 'pnpm tauri'
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
