name: "Test"
on: [push]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-ui
      - run: pnpm lint

  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-ui
      - run: pnpm check

  unittest-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-ui
      - run: pnpm test

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-tauri
      - run: cargo fmt --check
      - run: cargo install cargo-sort
      - run: cargo sort --check --workspace

  story:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-ui
      - run: pnpm story:build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-env-tauri
      - uses: ./.github/actions/init-env-ui
      - run: pnpm build
      - run: cargo clippy --all-features
      - run: cargo test --locked
