name: "Test"
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.x.x
                  run_install: |
                      args: ["--frozen-lockfile"]

            - name: Setup rust
              uses: dtolnay/rust-toolchain@stable
              run: |
                  # required to run tests
                  sudo apt-get install libgtk-3-dev

            - name: Test rust
              working-directory: src-tauri
              run: |
                  cargo test

            - name: Build tauri
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tauriScript: "pnpm tauri"
