name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm dlx playwright@1.40.0 install --with-deps chromium
      - name: Run ubuntu/chrome snapshots
        run: cd app && pnpm test:e2e
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 30
