name: E2E Tests Webdriver
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'apps/web/**'
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: false
        description: Target SHA

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.0
        with:
          shared-key: e2e-testing-cache
      # - name: Install OS dependencies
      #   run: |
      #     sudo apt update && sudo apt install -y \
      #       libsoup-3.0-0 \
      #       libgtk-3-dev \
      #       libayatana-appindicator3-dev \
      #       libwebkit2gtk-4.1-dev \
      #       webkit2gtk-driver \
      #       ffmpeg \
      #       xvfb
      - name: Setup rust-toolchain stable
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node environment
        uses: ./.github/actions/init-env-node
      - name: WebdriverIO
        run: pnpm test:e2e
      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-videos
          path: e2e/test-results/videos/
          retention-days: 30
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: e2e/test-results/
          retention-days: 7
