name: Playwright Tests
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm dlx playwright@1.40.0 install --with-deps chromium
      - name: Run Tests
        run: cd app && pnpm test:e2e
        env:
          CI: true
      - run: ls -lah .
      - run: ls -lah /home/runner/work/gitbutler/gitbutler/
      - run: ls -lah /home/runner/work/gitbutler/gitbutler/app/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: app/playwright-report/
          if-no-files-found: ignore
          retention-days: 30
